### ISSUE TITLE
20 Keys

### ISSUE THREAD

**Issue by ekendra-nz** [allanlw/builds-hackme#1]
Hello from New Zealand. 

Some students and I are new to CTF and cyber-security in general. 

They wanted to work on your CTF challenge:

http://ctf.slothparadise.com

Are there actually 20 keys as we could only find 10 of them?

**Comment by huyle333** [comment]
Originally, I think that Allan wanted to make 20, but he only put 10 on the site. @ekendra-nz

**Comment by ekendra-nz** [comment]
Thanks. They'll be happy to know they've exhausted the list.

**Comment by allanlw** [comment]
@huyle333 Can you change the code on the sloth paradise instance to say 10? I keep getting twitter DMs about it lol

**Comment by huyle333** [comment]
@allanlw I finally updated it manually =)
